### ISSUE TITLE
Bug: Preview Image not showing

### ISSUE THREAD

**Issue by SpiritDevGitHub** [Trico-Everfire/p2-publishing-tool#15]
When looking at one of my uploads the preview image is displayed as invalid.

OS: Windows 10/11

![image](https://user-images.githubusercontent.com/49439933/200882008-bcb0bdd9-48f4-4839-a992-acb047d8983e.png)

**Comment by Trico-Everfire** [comment]
When editing?

**Comment by Trico-Everfire** [comment]
If it's when editing, I know this has to be an issue with Steam API fetching the image. Can you send me the item that causes this? (the link to the workshop item) so I can investigate further?

**Comment by SpiritDevGitHub** [comment]
any of the levels listed on my workshop

https://steamcommunity.com/id/SpiritDev/myworkshopfiles/?appid=620

**Comment by Trico-Everfire** [comment]
to bump this, This issue should either be fixed or be more clear in https://github.com/Trico-Everfire/p2-publishing-tool/pull/19.

**Comment by Trico-Everfire** [comment]
This should no longer occur in newest release. If it still does, reopen issue.
