### ISSUE TITLE
"You don't have a Preview Image", even after inserting one.

### ISSUE THREAD

**Issue by fulano0esquerda** [Trico-Everfire/p2-publishing-tool#17]
![image](https://user-images.githubusercontent.com/83985990/206734459-2c7d574d-2923-493d-92ab-4c04bec974d5.png)
For some reason, regardless of the resolution, even after adding a Preview Image, the program seems to think that I haven't added a Preview Image yet. Neither the PNG or JPEG format works, with the only difference is that the JPEG one actually appears as "Invalid Image", while the PNG one appears normally, but the program gives the same error regardless of which format the Preview image is. This issue is present in both 1.0.0 and 1.0.1 release versions (which are the ones I tested).

**Comment by Trico-Everfire** [comment]
Can you send me the image in question? it's easier to locate the bug if I have the image in question. If you don't want to send the image, tell me it's resolution along with it's extension.

**Comment by fulano0esquerda** [comment]
> Can you send me the image in question? it's easier to locate the bug if I have the image in question. If you don't want to send the image, tell me it's resolution along with it's extension.
![reboot_main](https://user-images.githubusercontent.com/83985990/206740734-74c9e463-6f20-4d1c-b8a0-dfa95280ecdb.png)
Sure.

**Comment by Trico-Everfire** [comment]
This is odd. It works on my machine, I uploaded a test with the image and it successfully uploaded, according to the code the only thing able to trigger this message if you never inserted an image, however, this may be due to it's inability to save the current image as a thumbnail, causing it to never set it's path. I'll try to fix the issue and see how it works out. As for why the .png doesn't show at all, it's even stranger, but I'll see. it's likely either a permission issue (the application isn't allowed to create it's resources) or an issue with the way it tries to save the temporary resources.

**Comment by fulano0esquerda** [comment]
Okay, please let me know if you find out what's going on

**Comment by fulano0esquerda** [comment]
Alright, thanks

**Comment by fulano0esquerda** [comment]
Weird, I tried running it in Administator mode and it's still not working. The file size of the image doesn't seem to affect it either. I also tried to put the image inside the folder where the program is installed but had no effect.

**Comment by Trico-Everfire** [comment]
Where the image comes from doesn't really matter, it grabs the image from an absolute path. However, in the folder the .exe is housed in, can you add a directory with the name "resources", maybe it has trouble creating the directory.

**Comment by fulano0esquerda** [comment]
Wait, this is weird, the program is creating the "resources" folder normally when I select the image.
But again, when I tried to click "upload", it still gave this error.

**Comment by Trico-Everfire** [comment]
Is there an image inside the resources folder?

**Comment by fulano0esquerda** [comment]
There are no images inside the resources folder.

**Comment by Trico-Everfire** [comment]
This is what I feared, it is indeed unable to generate the image. My theory is that on windows the directory it creates is protected and won't allow itself to put anything inside. or something else is preventing it from working.

**Comment by fulano0esquerda** [comment]
What if I converted to fit the steam requirements and added the image there?

**Comment by Trico-Everfire** [comment]
I also have another theory, the library is unable to generate a JEPG, Which may be more likely at this point, this means it's a library error, and if so, I'd have to find and add the correct library. Can you try and run the uploader inside a command prompt and tell me what it logs when you try and upload an image, if there is an error when it tries to create the image, it'd likely spew an error of some kind, if not, I'll try my hand at a few solutions.

**Comment by fulano0esquerda** [comment]
![image](https://user-images.githubusercontent.com/83985990/206758423-e7938bec-015a-4883-b736-06d98fc040b1.png)
I just found out something. It's marking the folder to "read-only" every time I try to upload it. I unmarked it and tried upload it but then it marked the folder to "read-only" again and gave me the error.

**Comment by fulano0esquerda** [comment]
> I also have another theory, the library is unable to generate a JEPG, Which may be more likely at this point, this means it's a library error, and if so, I'd have to find and add the correct library. Can you try and run the uploader inside a command prompt and tell me what it logs when you try and upload an image, if there is an error when it tries to create the image, it'd likely spew an error of some kind, if not, I'll try my hand at a few solutions.

Okay, I'll try that

**Comment by fulano0esquerda** [comment]
For some reason, nothing's appearing in the command prompt when I run the program through it. I tried to upload the map, the program gave me the error and nothing appeared on it.

**Comment by Trico-Everfire** [comment]
I think the culprit has been found. mkdir in QT calls whatever API your OS is responsible for with no knowledge of permissions, It simply doesn't understand that what it's creating is incapable of being used.

**Comment by fulano0esquerda** [comment]
So, what would be the solution?

**Comment by fulano0esquerda** [comment]
I mean, I guess maybe I could try running it on a Linux Subsystem?

**Comment by Trico-Everfire** [comment]
You could, but I wanna fix it so it works on both platforms as advertised.

**Comment by fulano0esquerda** [comment]
Meanwhile, is there anything I could do to help?

**Comment by Trico-Everfire** [comment]
Currently no. This cause of issue with the folder may also be the reason on why Issue #15 exists, simply because it's trying to download those preview images, but never gets to do so because it's marked as readonly.

**Comment by Trico-Everfire** [comment]
I can provide you with a experimental copy that comes with a resources folder pre created, it removes the code responsible for creating it thus forever marking it as writable.

**Comment by Trico-Everfire** [comment]
A friend suggested to not put the uploader's binaries (and other files it comes with) not in Program Files, that may be protected, I will looking for a fix.

**Comment by fulano0esquerda** [comment]
Oh, right. I guess it could be it as well.

**Comment by fulano0esquerda** [comment]
Hm, Still didn't work.

**Comment by fulano0esquerda** [comment]
> I can provide you with a experimental copy that comes with a resources folder pre created, it removes the code responsible for creating it thus forever marking it as writable.

Oh yeah, please do. Setting up Ubuntu is really annoying, lol

**Comment by Trico-Everfire** [comment]
It'll have to be later, my IDE is having a stroke and refuses to function.

**Comment by fulano0esquerda** [comment]
Okay

**Comment by Trico-Everfire** [comment]
Can you try this?

<https://pipelines.actions.githubusercontent.com/serviceHosts/19566cf5-b296-4bf7-b2c1-7204eeca1707/_apis/pipelines/1/runs/81/signedartifactscontent?artifactName=p2-publishing-tool-windows-Release&urlExpires=2022-12-09T20%3A53%3A52.6387725Z&urlSigningMethod=HMACV2&urlSignature=jL%2BE3%2FehamawOPwQFxiV0nJ8eyK%2FbvsKeAN3VxQfhDY%3D>

**Comment by Trico-Everfire** [comment]
I tried using the C++ standard library for creating the directories, which apparently hopefully does a better job than QT.

**Comment by fulano0esquerda** [comment]
{"count":11,"value":"Uri expired"}

**Comment by Trico-Everfire** [comment]
[p2-publishing-tool-windows-Release.zip](https://github.com/Trico-Everfire/p2-publishing-tool/files/10198239/p2-publishing-tool-windows-Release.1.zip)

**Comment by fulano0esquerda** [comment]
Thanks.

**Comment by fulano0esquerda** [comment]
![image](https://user-images.githubusercontent.com/83985990/206799948-b016c929-59ee-4e6b-bee3-588c80bf5c52.png)
Oof

**Comment by Trico-Everfire** [comment]
Okay, please hold on for a minute.

**Comment by Trico-Everfire** [comment]
[p2-publishing-tool-windows-Release.zip](https://github.com/Trico-Everfire/p2-publishing-tool/files/10198355/p2-publishing-tool-windows-Release.2.zip)

**Comment by Trico-Everfire** [comment]
This one you currently have to add the folder yourself.

**Comment by Trico-Everfire** [comment]
it will not even attempt to create one.

**Comment by fulano0esquerda** [comment]
Okay, cool.

**Comment by fulano0esquerda** [comment]
![image](https://user-images.githubusercontent.com/83985990/206803935-f918d00c-98bf-4091-990e-ccaa77b5c4f5.png)
What the hell

**Comment by Trico-Everfire** [comment]
is the folder empty?

**Comment by fulano0esquerda** [comment]
Hm, I don't think the folder was being set to Read-Only anymore, it's still not working.

**Comment by fulano0esquerda** [comment]
and yeah, it's empty

**Comment by Trico-Everfire** [comment]
I don't know what's causing this, but I'll take a look at it later, I've never experienced something like this before.

**Comment by fulano0esquerda** [comment]
Yeah, and I gotta go now. I hope you can find something that can help you fix this problem.

**Comment by fulano0esquerda** [comment]
I have an idea, how about you try to make a version that allows you to upload the map with a placeholder thumbnail to change it on steam later?

**Comment by fulano0esquerda** [comment]
Also, what are the requirements for the Linux version?

**Comment by Trico-Everfire** [comment]
Uhm, the linux version should just work, if it doesn't, That's a new issue entirely.

**Comment by Trico-Everfire** [comment]
I have an idea to fix this, it's due to something I discovered when working on another tool. I'll provide you a build soon.

**Comment by Trico-Everfire** [comment]
[Uploading p2-publishing-tool-windows-Release.zip…]()

**Comment by Trico-Everfire** [comment]
[p2-publishing-tool-windows-Release.zip](https://github.com/Trico-Everfire/p2-publishing-tool/files/10240381/p2-publishing-tool-windows-Release.1.zip)

**Comment by fulano0esquerda** [comment]
Alright. Again, thank you very much!
Also, about the "requirements", I thought the release version needed me to install a few libraries but I noticed that I didn't need them since the program was already built, and even so, it's giving me errors saying that it could not be executed even though the binaries are being found...? I think I might have done something wrong in the set up, but I'm not sure what since there isn't really a guide on how to do it.

**Comment by Trico-Everfire** [comment]
On the linux build? The linux build seems to just have issues unless you build it yourself, QT is sturdy on what you need to pack with it, and it's what lead to many of the issues we face now. I need to go back and see things through properly, currently taking a small break (fixing a bug for multiple days at the time without squashing it takes a tole on someone :smile:.

**Comment by fulano0esquerda** [comment]
I managed to publish the map, by the way, and I edited its tags but there seems to be another issue
Editing a tag doesn't seem to be enough for the program to know that you did something, I had to edit my description as well and clicking update. When it does update the maps, the window just doesn't seem to close even after the changes have already been made, and I had to close it manually.

**Comment by Trico-Everfire** [comment]
Ah, I may have forgotten to check if tags have changed, it doesn't bother to actually update if it thinks nothing changed, I'll have to look into that.

**Comment by Trico-Everfire** [comment]
to bump this, This issue should either be fixed or be more clear in #19.

**Comment by fulano0esquerda** [comment]
Yes, it got fixed with the re-write.
