### ISSUE TITLE
Rewrite: Complete rewrite of the tool.

### ISSUE THREAD

**Issue by Trico-Everfire** [Trico-Everfire/p2-publishing-tool#18]
I've decided that this tool sucks, the code is bad, it's buggy on Windows and has problems here and there. So, I'm rewriting it, this time with a bit more overhead and hopefully more skill.

- [x] Entry View Window.
- [x] Standard upload functionality.
- [x] Edit existing entries
- [x] Advanced options.
- [x] Comprehensive Error Display.
- [x] Cleanup and Refactor. 

If there should be more added to this issue, or like to discuss the points listed, please reply to this Issue.

The rewrite will happen on the `new/rewrite` branch.

**Comment by jple777** [comment]
Hi!
Do you have any new version?
I tried the latest one on Win10 and the Image Preview problem is still there (Invalid)...
If I try to Edit, without touching the preview, it seems to work, but actually nothing is loaded..
Also some of the maps on the workshop are not in the list.
I hope this can be fixed because for me the p2map_publish is not working anymore, for some reason :(
Have a cool day anyway :D

**Comment by Trico-Everfire** [comment]
I am rewriting the tool in it's entirety, which, (hopefully) should fix any issues people may have with the tool. The old code was sketchy at best and I am surprised it even worked. Although I haven't been able to properly test it, my suspicion on why the uploader fails now is because of permission issues on Windows, but I have no ways of properly testing this, after this rewrite (which is coming along really nicely (almost ready to check a few of the boxes),  So keep tabs on this issue specifically, because I do plan on posting more when I have more stuff done and cleaned up.

**Comment by jple777** [comment]
Hi!
Glad to know that you’re still on the project :)
I will sure test it as soon as you post it.
Thanks for your work!
jp

**Comment by Trico-Everfire** [comment]
Everything is currently "functional", I cannot test 100MB+ upload functionality, simply because I do not have a 100MB BSP, but theoretically, it should upload. All that is left besides that is refactoring.

**Comment by Trico-Everfire** [comment]
100+ MB BSPs seem to work, but the application has a bit of trouble with them.

**Comment by Trico-Everfire** [comment]
Final changes are being made, it's almost ready for public beta.
Though, remember that, Beta, not final.

**Comment by jple777** [comment]
Hi!

I hope I will be able to test it a bit later, but for the moment, I got a serious prob: my Steam Cloud is full.
Uploading or updating any map gives an error message, and according to Steam Support, this is because I reached the limit of 1GB on my cloud. (That makes sense because most of my Hammer maps are around 150MB.)
So for the moment I can't do any test :(  and I probably will need to open a new account...

This also means that the first tests I did (see previous messages) were not relevant, except for the "invalid image preview" problem.
I'll get back to it asap..
jp

**Comment by Trico-Everfire** [comment]
if I recall, the steam storage that's full can be cleared, this does, as far as I know, not get rid of your workshop maps, rather just removes them from your steam storage.

**Comment by Trico-Everfire** [comment]
> This also means that the first tests I did (see previous messages) were not relevant, except for the "invalid image preview" problem.

` "invalid image preview"`
was caused by Windows being unable to save the file, it tried, failed, continued and didn't find the image because it was never saved, marking the process as invalid. the current system immediately warns you if it's unable to create files. At which point, it's probably a firewall problem, or another windows related issue. Windows is very protective of what can and can't create files, and I don't know where QT exactly lies in this, because a lot of QT applications I use can create files just fine. so, it's something I would have to have people test. As for currently, there is still a bit of code I'd like to push before I want ppl to test it, however, I am currently on a small break (have been working 7 days straight on this, wanna do a little bit of other stuff.) and should get back to it soon, thanks for the patience tho.

**Comment by Trico-Everfire** [comment]
The public beta has begun! No binaries yet, that'll come later on. Feel free to download, requiring QT 6.4.1 to work, Success!

[BETA BRANCH](https://github.com/Trico-Everfire/p2-publishing-tool/tree/new/rewrite)

**Comment by Trico-Everfire** [comment]
https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v2.0.0-beta

**Comment by jple777** [comment]
No .exe ?

**Comment by Trico-Everfire** [comment]
This contains the exe:
https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v2.0.0-beta

**Comment by Trico-Everfire** [comment]
I'll be honest, it's difficult to compile stuff for windows when you're a linux user.

**Comment by jple777** [comment]
I'm on Win 10 on a Mac via Bootcamp.
Did you send the exe already?

**Comment by Trico-Everfire** [comment]
I am busy trying to get QT6 onto my old windows 10 laptop. it'll take a while before that'll work. not too long, but, I'd say within the next 2 hours.

**Comment by Trico-Everfire** [comment]
@jple777 fixed!

**Comment by jple777** [comment]
Hi!
I tested it but it's not working by me.
This is what I get:
![Screenshot (40)](https://user-images.githubusercontent.com/86750790/219901348-9015d83f-7376-4a2d-84c1-bc100a48684d.png)

(The message is showing for 2 sec then disappear)

**Comment by Trico-Everfire** [comment]
Oh my god! I need SSL stuff?!

**Comment by Trico-Everfire** [comment]
Welp, that's why this is a beta, so stuff like this can be noticed and fixed.

**Comment by Trico-Everfire** [comment]
SSL fix supplied in new release.

**Comment by jple777** [comment]
I have to leave now but I can test it tomorrow..
Cya!

**Comment by Trico-Everfire** [comment]
Okay.
