### ISSUE TITLE
Bug: Unable to upload BSP, Error.

### ISSUE THREAD

**Issue by Trico-Everfire** [Trico-Everfire/p2-publishing-tool#21]
2 testers have reported being unable to upload BSPs, enough to warrent inverstigation.

**Comment by jple777** [comment]
Same here, retrieving of files is ok; adding new files is not working, see screenshot
![Screenshot (43)](https://user-images.githubusercontent.com/86750790/221296986-00a808a4-9272-4317-833c-f09f4e1ec6eb.png)

**Comment by jple777** [comment]
(The same file is uploading with the regular p2map_publish)

**Comment by Trico-Everfire** [comment]
Yup, it's a confirmed bug now, I will have to investigate it, thanks.

**Comment by Trico-Everfire** [comment]
problem has been identified and issue will be closed in next release!

**Comment by Trico-Everfire** [comment]
https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v2.0.5-beta
