### ISSUE TITLE
still comes up with "steam must be running" error

### ISSUE THREAD

**Issue by TheTrueFax** [Trico-Everfire/p2-publishing-tool#27]
it still comes up with it here is a screenshot
![Screenshot (2)](https://github.com/Trico-Everfire/p2-publishing-tool/assets/130262457/be6fa38e-a7ab-44ae-9ba5-429aa235670f)

**Comment by TheTrueFax** [comment]
heolp

**Comment by Trico-Everfire** [comment]
Closing until further response.

**Comment by TheTrueFax** [comment]
I fixed it you don't need any tools.
All you have to do is reinstall portal 2 and that
gives it a little kick to make it work.
