### ISSUE TITLE
[BUG] Force opens a console window on windows

### ISSUE THREAD

**Issue by ENDERZOMBI102** [Trico-Everfire/p2-publishing-tool#3]
To reproduce
-
- Download latest release (0.1) for windows
- Launch the app
- ~Profit~ Console opens

**Comment by AWildErin** [comment]
A fix for this could be `add_executable(editor WIN32 ${SRC})` though I don't know how well that would fair on Linux systems, Trico can test that out

**Comment by craftablescience** [comment]
i thought i fixed this in release

**Comment by AWildErin** [comment]
apparently not

**Comment by craftablescience** [comment]
yeah the console window doesnt show up for me
