### ISSUE TITLE
[FEATURE REQUEST] Dark mode

### ISSUE THREAD

**Issue by ENDERZOMBI102** [Trico-Everfire/p2-publishing-tool#5]
It would be awesome to have dark mode, as my eyes are already dying

**Comment by AWildErin** [comment]
`main.cpp` already has code for this, it was just never uncommented for whatever reason

**Comment by Trico-Everfire** [comment]
> `main.cpp` already has code for this, it was just never uncommented for whatever reason

This is because Fusion (the current style) clashes with the theme. I cannot combine them out of the box.
