### ISSUE TITLE
Linux: libsteam_api.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Bohmthedudevulture** [Trico-Everfire/p2-publishing-tool#6]
In Linux, when trying to execute the binary in the extracted folder give the error message:
`./p2_map_publisher: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`
the ls in the folder of the binary:
```
Credits.txt
libQt5Core.so
libQt5Gui.so
libQt5Network.so
libQt5Widgets.so
libsteam_api.so
p2_map_publisher
```

**Comment by Trico-Everfire** [comment]
Question, what distro of linux are you running? Even when installing the release it sees all files.

**Comment by realbeing2453tyhr** [comment]
OpenSUSE Leap 15.3
What are you referring with "Even when installing the release it sees all files"?

**Comment by realbeing2453tyhr** [comment]
For replicate this bug I made this script.
```bash
#!/usr/bin/bash -e

echo Downloading
curl -Lo p2-publishing-tool-linux-release.zip https://github.com/Trico-Everfire/p2-publishing-tool/releases/download/v0.2.0-alpha/p2-publishing-tool-linux-release.zip
echo Downloaded

echo Unziping
unzip p2-publishing-tool-linux-release.zip
echo Unzipped

echo Enabling execution
chmod +x p2_map_publisher
echo Execution is enabled

echo Runnig p2_map_publisher
./p2_map_publisher
```
I am executing it at /home/<insert suername>/Downloads/test.
And it gives me the following output
```
Downloading
Downloaded
Unziping
Archive:  p2-publishing-tool-linux-release.zip
  inflating: p2_map_publisher        
  inflating: libsteam_api.so         
  inflating: libQt5Widgets.so        
  inflating: libQt5Network.so        
  inflating: libQt5Gui.so            
  inflating: libQt5Core.so           
  inflating: Credits.txt             
Unzipped
Enabling execution
Execution is enabled
Runnig p2_map_publisher
./p2_map_publisher: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
```

**Comment by Trico-Everfire** [comment]
I figured out that it doesn't link the libraries properly, I'll fix this asap.

**Comment by Trico-Everfire** [comment]
> For replicate this bug I made this script.
> 
> ```shell
> #!/usr/bin/bash -e
> 
> echo Downloading
> curl -Lo p2-publishing-tool-linux-release.zip https://github.com/Trico-Everfire/p2-publishing-tool/releases/download/v0.2.0-alpha/p2-publishing-tool-linux-release.zip
> echo Downloaded
> 
> echo Unziping
> unzip p2-publishing-tool-linux-release.zip
> echo Unzipped
> 
> echo Enabling execution
> chmod +x p2_map_publisher
> echo Execution is enabled
> 
> echo Runnig p2_map_publisher
> ./p2_map_publisher
> ```
> 
> I am executing it at /home/<insert username>/Downloads/test. And it gives me the following output
> 
> ```
> Downloading
> Downloaded
> Unziping
> Archive:  p2-publishing-tool-linux-release.zip
>   inflating: p2_map_publisher        
>   inflating: libsteam_api.so         
>   inflating: libQt5Widgets.so        
>   inflating: libQt5Network.so        
>   inflating: libQt5Gui.so            
>   inflating: libQt5Core.so           
>   inflating: Credits.txt             
> Unzipped
> Enabling execution
> Execution is enabled
> Runnig p2_map_publisher
> ./p2_map_publisher: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
> ```

Can you attempt the newest release:
https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v0.2.2-alpha

it should fix the issues you have. if not, tell me ASAP.

**Comment by Bohmthedudevulture** [comment]
No sure if the problem may still exist after this other one:
./p2_map_publisher: /usr/lib64/libQt5Core.so.5: version `Qt_5.15' not found (required by ./p2_map_publisher)
This is because my system uses libQt5Core.so.5.12.7

**Comment by Bohmthedudevulture** [comment]
@Trico-Everfire No sure if the problem may still exist after this other one:
./p2_map_publisher: /usr/lib64/libQt5Core.so.5: version `Qt_5.15' not found (required by ./p2_map_publisher)
This is actually another bug?.
Clearly is trying to load system-wide libraries instead of the ones you provided.

**Comment by Trico-Everfire** [comment]
> @Trico-Everfire No sure if the problem may still exist after this other one: ./p2_map_publisher: /usr/lib64/libQt5Core.so.5: version `Qt_5.15' not found (required by ./p2_map_publisher) This is actually another bug?. Clearly is trying to load system-wide libraries instead of the ones you provided.

@Bohmthedudevulture 
it's odd, I'll have to look into it, It seems like that for whatever reason it tries to look for global libs, which it shouldn't.

**Comment by Bohmthedudevulture** [comment]
@Trico-Everfire Maybe should you try to remove global mentions in the CMake file?

**Comment by Bohmthedudevulture** [comment]
@Trico-Everfire The eror changes for `./p2_map_publisher: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory` after run `mv libQt5Core.so.5.15.2 libQt5Core.so.5`. This looks like the library is searching for the incorrect name in the search phase, probably it would still solve the problem with the other libraries, but before confirming someone have to fix this new error message.

**Comment by Bohmthedudevulture** [comment]
@Trico-Everfire I am pretty sure that you need to solve ship a copy of `libicui18n.so.56` in your build.

**Comment by Bohmthedudevulture** [comment]
I made a symbolic link for the missing `libicui18n.so.56`,  `libicuuc.so.56`, and `libicudata.so.56`. And change the name of the shipped libraries striping them of the last numbers afer the 5. And I resolves all the problems, except for the fact that the version of  `libicui18n.so.56`,  `libicuuc.so.56`, and `libicudata.so.56, aren't the correct ones, thus it does  not run.

**Comment by Bohmthedudevulture** [comment]
@Trico-Everfire  I take the opportunity of test my recommendations with a freshly compiled version of lib ICU from github.com/unicode-org/icu and the result is this new error: `qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
` by the recommendation of this stackoverflow https://stackoverflow.com/questions/62391587/qt-could-not-find-the-qt-platform-plugin-xcb it most likely have to do with the Qt libraries that you are shiping do no include the Qt xbc extension.

**Comment by Trico-Everfire** [comment]
@Bohmthedudevulture This has been resolved! Thank you for waiting.
[gcc_64](https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v1.0.1-Release)
I'll close this issue with this comment, if issues arise, please be sure to reopen this issue.
